### ISSUE TITLE
cant update libout123-devel-1.23.1-1.fc24.x86_64

### ISSUE THREAD

**Issue by mrpg99** [UnitedRPMs/packages#23] opened 2016-05-13 15:29 UTC
Hi, i am having the following issue 

```
[17:27:22] mrpg@govpg:[~]: sudo dnf update
Last metadata expiration check: 0:09:38 ago on Fri May 13 17:17:47 2016.
Dependencies resolved.
==============================================================================================================================
 Package                                  Arch                  Version                       Repository                 Size
==============================================================================================================================
Skipping packages with broken dependencies:
 libmpg123                                x86_64                1.23.3-1.fc24                 unitedrpms                205 k
 libmpg123-devel                          x86_64                1.23.3-1.fc24                 unitedrpms                309 k
 mpg123                                   x86_64                1.23.3-1.fc24                 unitedrpms                115 k
 mpg123-plugins-extras                    x86_64                1.23.3-1.fc24                 unitedrpms                 26 k
 mpg123-plugins-jack                      x86_64                1.23.3-1.fc24                 unitedrpms                 17 k
 mpg123-plugins-pulseaudio                x86_64                1.23.3-1.fc24                 unitedrpms                 14 k

Transaction Summary
==============================================================================================================================
Skip  6 Packages

Nothing to do.
Complete!

[17:27:27] mrpg@govpg:[~]: sudo dnf upgrade --best --allowerasing
Last metadata expiration check: 0:10:19 ago on Fri May 13 17:17:47 2016.
Error: package libout123-devel-1.23.1-1.fc24.x86_64 requires libmpg123(x86-64) = 1.23.1-1.fc24, but none of the providers can be installed
```

Best Regards
Patric Gustavsson

**Comment by paulcarroty** [comment] 2016-05-13 16:09
@mrpg99 try uninstall `libout123-devel`:

```
# dnf erase libout123-devel
```

and paste the output here.

Cast @kuboosoft as maintainer of `mpg`.

**Comment by mrpg99** [comment] 2016-05-13 16:52
Hi Paul,[18:50:28] mrpg@govpg:[~]: sudo dnf erase libout123-devel-1.23.1-1.fc24.x86_64 
[sudo] password for mrpg: 
Dependencies resolved.
================================================================================
 Package                Arch          Version              Repository      Size
================================================================================
Removing:
 libout123-devel        x86_64        1.23.1-1.fc24        @System         29 k

Transaction Summary
================================================================================
Remove  1 Package

Installed size: 29 k
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Erasing     : libout123-devel-1.23.1-1.fc24.x86_64                        1/1 
  Verifying   : libout123-devel-1.23.1-1.fc24.x86_64                        1/1 

Removed:
  libout123-devel.x86_64 1.23.1-1.fc24                                          

Complete!
[18:50:54] mrpg@govpg:[~]: sudo dnf update
Last metadata expiration check: 1:33:14 ago on Fri May 13 17:17:47 2016.
Dependencies resolved.
================================================================================
 Package                      Arch      Version             Repository     Size
================================================================================
Upgrading:
 libmpg123                    x86_64    1.23.3-1.fc24       unitedrpms    205 k
 libmpg123-devel              x86_64    1.23.3-1.fc24       unitedrpms    309 k
 mpg123                       x86_64    1.23.3-1.fc24       unitedrpms    115 k
 mpg123-plugins-extras        x86_64    1.23.3-1.fc24       unitedrpms     26 k
 mpg123-plugins-jack          x86_64    1.23.3-1.fc24       unitedrpms     17 k
 mpg123-plugins-pulseaudio    x86_64    1.23.3-1.fc24       unitedrpms     14 k

Transaction Summary
================================================================================
Upgrade  6 Packages

Total download size: 686 k
Is this ok [y/N]: y
Downloading Packages:
(1/6): libmpg123-1.23.3-1.fc24.x86_64.rpm       213 kB/s | 205 kB     00:00    
(2/6): mpg123-1.23.3-1.fc24.x86_64.rpm          113 kB/s | 115 kB     00:01    
(3/6): libmpg123-devel-1.23.3-1.fc24.x86_64.rpm 293 kB/s | 309 kB     00:01    
(4/6): mpg123-plugins-extras-1.23.3-1.fc24.x86_  81 kB/s |  26 kB     00:00    
(5/6): mpg123-plugins-jack-1.23.3-1.fc24.x86_64  46 kB/s |  17 kB     00:00    
(6/6): mpg123-plugins-pulseaudio-1.23.3-1.fc24.  33 kB/s |  14 kB     00:00    
--------------------------------------------------------------------------------
Total                                           489 kB/s | 686 kB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/lib64/libout123.so.0.1.1 from install of libmpg123-1.23.3-1.fc24.x86_64 conflicts with file from package libout123-1.23.1-1.fc24.x86_64

Error Summary
-------------

**Comment by paulcarroty** [comment] 2016-05-13 17:42
So, Patric, the one and only app what requires `libmpg123` is `idjc`. We need to rebuild it. You can wait or delete `libmpg123` & `idjs`.

**Comment by mrpg99** [comment] 2016-05-13 18:22
hi i tried to remove libmpg123 , but it then wants to remove all of this 

[20:21:39] mrpg@govpg:[~]: sudo dnf erase libmpg123-1.23.1-1.fc24.x86_64 
Dependencies resolved.
================================================================================
 Package               Arch   Version                         Repository   Size
================================================================================
Removing:
 ftgl                  x86_64 2.1.3-0.14.rc5.fc24             @fedora     390 k
 gstreamer1-plugins-ugly
                       x86_64 1.8.1-1.fc24                    @enjoy24    770 k
 gstreamer1-plugins-ugly-devel-docs
                       noarch 1.8.1-1.fc24                    @enjoy24    262 k
 libcddb               x86_64 1.3.2-19.fc24                   @fedora     201 k
 libebml               x86_64 1.3.3-3.fc24                    @fedora     232 k
 libmatroska           x86_64 1.4.4-2.fc24                    @fedora     760 k
 libmpg123             x86_64 1.23.1-1.fc24                   @System     453 k
 libprojectM           x86_64 2.1.0-1.fc24                    @fedora     2.1 M
 libtiger              x86_64 0.3.4-11.fc24                   @fedora      81 k
 libupnp               x86_64 1.6.19-5.fc24                   @fedora     226 k
 libvncserver          x86_64 0.9.10-5.fc24                   @fedora     813 k
 lzo-minilzo           x86_64 2.08-8.fc24                     @fedora      36 k
 minizip               x86_64 1.2.8-10.fc24                   @fedora      50 k
 mpg123                x86_64 1.23.1-1.fc24                   @System     278 k
 mpg123-plugins-extras x86_64 1.23.1-1.fc24                   @local       51 k
 mpg123-plugins-jack   x86_64 1.23.1-1.fc24                   @System      20 k
 mpg123-plugins-pulseaudio
                       x86_64 1.23.1-1.fc24                   @System      12 k
 nas-libs              x86_64 1.9.4-7.fc24                    @fedora     185 k
 perl-XML-XPath        noarch 1.36-1.fc24                     @updates-testing
                                                                          199 k
 portaudio             x86_64 19-23.fc24                      @fedora     254 k
 texlive-base          noarch 5:2015-24.20150728_r37987.fc24  @fedora     8.2 M
 texlive-gnu-freefont  noarch 5:svn29349.0-24.fc24.1          @fedora      17 M
 texlive-hyphen-base   noarch 5:svn34525.0-24.fc24.1          @fedora      62 k
 texlive-kpathsea      noarch 5:svn37193.0-24.fc24.1          @fedora     215 k
 texlive-kpathsea-bin  x86_64 5:svn37207.0-24.20150728_r37987.fc24.1
                                                              @fedora      83 k
 texlive-metafont      noarch 5:svn37078.2.7182818-24.fc24.1  @fedora     120 k
 texlive-metafont-bin  x86_64 5:svn36790.0-24.20150728_r37987.fc24.1
                                                              @fedora     625 k
 texlive-tetex         noarch 5:svn38208.3.0-24.fc24.1        @fedora     308 k
 texlive-tetex-bin     noarch 5:svn36770.0-24.20150728_r37987.fc24.1
                                                              @fedora       0  
 texlive-texlive.infra noarch 5:svn37738.0-24.fc24.1          @fedora     462 k
 texlive-texlive.infra-bin
                       x86_64 5:svn36790.0-24.20150728_r37987.fc24.1
                                                              @fedora       0  
 vlc                   x86_64 3.0.0-5.20160506gitfa5c292.fc24 @unitedrpms 4.1 M
 vlc-core              x86_64 3.0.0-5.20160506gitfa5c292.fc24 @unitedrpms  38 M
 vlc-devel             x86_64 3.0.0-5.20160506gitfa5c292.fc24 @unitedrpms 879 k
 vlc-extras            x86_64 3.0.0-5.20160506gitfa5c292.fc24 @unitedrpms  68 k
 vlc-plugin-jack       x86_64 3.0.0-5.20160506gitfa5c292.fc24 @unitedrpms  30 k

Transaction Summary
================================================================================
Remove  36 Packages

Installed size: 78 M
Is this ok [y/N]: n

**Comment by paulcarroty** [comment] 2016-05-13 18:56
@mrpg99 sorry for my mistake - the `libout123`, not `libmpg123`.

**Comment by mrpg99** [comment] 2016-05-13 21:20
thank you m8, this sorted it out!

**Comment by kuboosoft** [comment] 2016-05-14 08:11
Well; I updated the libmpeg123;  While the repository is sync; also you can install manually... 
https://github.com/UnitedRPMs/mpg123/tree/master/RPM @mrpg99

**Comment by paulcarroty** [comment] 2016-05-14 08:15
@kuboosoft this is major update? We need to rebuild some packages?

**Comment by kuboosoft** [comment] 2016-05-14 08:24
@paulcarroty  . No, but is necessary update, please read here (http://www.mpg123.de/) I have installed all packages without problem; the best way to test broken packages is with mock...
The issue is very strange because libout123-devel isn't provided in none rpm here... maybe a autoreq/prov issue?

**Comment by paulcarroty** [comment] 2016-05-14 12:00
@kuboosoft @mrpg99  merged new mpg123 and rebuild idjc!
@sergiomb2 please sync the mirror.

**Comment by kuboosoft** [comment] 2016-05-14 16:51
idjc; isn't affected but test it; I installed 'idjc' after mpg123 without problem @paulcarroty @sergiomb2

**Comment by sergiomb2** [comment] 2016-05-14 18:02
hello , I'd like rebuild and republish kodi-pvr , with correct jsoncpp (the one from Fedora proper with hackings) https://github.com/UnitedRPMs/platform-compat/issues/1 ,
Also if you agree remove json06 and json07 from repos , what do you think ?

**Closed** 2016-05-16 01:03 UTC
